package com.mercury.domain;

// Generated 2016-2-18 11:51:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */

/**
 * CREATE TABLE `sys_user` (
 *   `user_id` bigint(32) NOT NULL AUTO_INCREMENT COMMENT '用户id',
 *   `user_code` varchar(32) NOT NULL COMMENT '用户账号',
 *   `user_name` varchar(64) NOT NULL COMMENT '用户名称',
 *   `user_password` varchar(32) NOT NULL COMMENT '用户密码',
 *   `user_state` char(1) NOT NULL COMMENT '1:正常,0:暂停',
 *   PRIMARY KEY (`user_id`)
 * ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
 */
public class User implements java.io.Serializable {

    private Long userId;
    private String userCode;
    private String userName;
    private String userPassword;
    private String userState;
    //客户拜访记录
    private Set saleVisits = new HashSet(0);
    //一个用户可以有多个角色
    private Set sysRoles = new HashSet(0);



    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserCode() {
        return this.userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public String getUserState() {
        return this.userState;
    }

    public void setUserState(String userState) {
        this.userState = userState;
    }


    public Set getSysRoles() {
        return this.sysRoles;
    }

    public void setSysRoles(Set sysRoles) {
        this.sysRoles = sysRoles;
    }

    public Set getSaleVisits() {
        return saleVisits;
    }

    public void setSaleVisits(Set saleVisits) {
        this.saleVisits = saleVisits;
    }


    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", userCode='" + userCode + '\'' +
                ", userName='" + userName + '\'' +
                ", userPassword='" + userPassword + '\'' +
                ", userState='" + userState + '\'' +
                '}';
    }
}

